image: Visual Studio 2022

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  VS_VERSION: 2022

build: off

init:
  # タイムゾーンを JST に変更
  - tzutil /s "Tokyo Standard Time"
  # c:\cygwin64 の Cygwin に cmake をインストール
  # このコマンドではインストール済みパッケージは更新されない
  - c:\cygwin64\setup-x86_64.exe --quiet-mode --packages cmake

cache:
  - libs

build_script:
  - ci_scripts/build_appveyor_release_bat.bat
  - ci_scripts/build_appveyor_release_bat_pre_cache.bat

artifacts:
  - path: installer/Output/*.exe
  - path: installer/Output/*.zip

on_success:
  - ci_scripts\notify.bat success
on_failure:
  - ci_scripts\notify.bat failure
on_finish:
# ビルド完了後に RDP が有効になる。blockRdp を指定しているので、完了後にも終了しない。
# - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
